# Generated by Django 5.0.6 on 2024-09-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('tag_searched', models.CharField(max_length=255)),
                ('block_record', models.TextField()),
                ('location_of_tag', models.CharField(max_length=100)),
                ('date_of_search', models.DateField()),
                ('search_author', models.CharField(max_length=100)),
                ('match_type', models.CharField(choices=[('exact', 'Exact Match'), ('partial', 'Partial Match')], max_length=10)),
                ('other', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
