# Generated by Django 5.0.6 on 2024-09-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_parser', '0002_extracteddata_search_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddata',
            name='line_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
