# Generated by Django 5.0.6 on 2024-09-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_parser', '0003_extracteddata_line_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracteddata',
            name='date_of_search',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
