# Generated by Django 5.0.6 on 2024-09-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_parser', '0004_alter_extracteddata_date_of_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracteddata',
            name='line_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='location_of_tag',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='search_author',
            field=models.CharField(max_length=255),
        ),
    ]
